// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDf9tZ3z45v_bf4oo3jKChVlwXJczaQKqI',
    appId: '1:983931527078:web:6706aaf59ddf2334f27967',
    messagingSenderId: '983931527078',
    projectId: 'pdftool-7166b',
    authDomain: 'pdftool-7166b.firebaseapp.com',
    storageBucket: 'pdftool-7166b.firebasestorage.app',
    measurementId: 'G-3EJ9NV502Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD27BiWQxQ8YFeRYepGXpSnPF-O9GwCRUI',
    appId: '1:983931527078:android:689e04db6de2614af27967',
    messagingSenderId: '983931527078',
    projectId: 'pdftool-7166b',
    storageBucket: 'pdftool-7166b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMFK9-uBTOd8Z-BnhjyYryKcK4HW-UHQg',
    appId: '1:983931527078:ios:f3f3e2188838fb08f27967',
    messagingSenderId: '983931527078',
    projectId: 'pdftool-7166b',
    storageBucket: 'pdftool-7166b.firebasestorage.app',
    iosBundleId: 'com.example.pdftool',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMFK9-uBTOd8Z-BnhjyYryKcK4HW-UHQg',
    appId: '1:983931527078:ios:f3f3e2188838fb08f27967',
    messagingSenderId: '983931527078',
    projectId: 'pdftool-7166b',
    storageBucket: 'pdftool-7166b.firebasestorage.app',
    iosBundleId: 'com.example.pdftool',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDf9tZ3z45v_bf4oo3jKChVlwXJczaQKqI',
    appId: '1:983931527078:web:22cb54dc2777578ff27967',
    messagingSenderId: '983931527078',
    projectId: 'pdftool-7166b',
    authDomain: 'pdftool-7166b.firebaseapp.com',
    storageBucket: 'pdftool-7166b.firebasestorage.app',
    measurementId: 'G-92LK8EX5BX',
  );

}